othermsite/web/othermdbapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf.urls import include, re_path
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views
from django.contrib.auth.decorators import user_passes_test

from . import views as otherm_views

router = DefaultRouter()
router.register(r'equipment', otherm_views.EquipmentViewSet, basename='equipment')
router.register(r'weather_station', otherm_views.WeatherStationViewSet, basename='weather_station')
router.register(r'site', otherm_views.SiteViewSet, basename='site')
router.register(r'monitoring_system', otherm_views.MonSysViewSet, basename='monitoring_system')
router.register(r'equipment_monitoring', otherm_views.EquipmentMonitoringViewSet, basename='equipment_monitoring')
router.register(r'thermal_source', otherm_views.SiteSourceMapViewSet, basename='thermal_source')
router.register(r'equipment_specs', otherm_views.EquipmentModelViewSet, basename='equipment_specs')
router.register(r'thermal_load', otherm_views.SiteThermalLoadViewSet, basename='thermal_load')
router.register(r'equipment_data', otherm_views.EquipmentDataViewSet, basename='equipment_data')

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', otherm_views.CustomAuthToken.as_view()),
    path('', otherm_views.index, name='index'),
    path('sites/', otherm_views.SitePageView.as_view(), name='sites'),
    path('site-forms/', otherm_views.site_forms, name='site-forms'),
    path('admin-forms/', otherm_views.admin_forms, name='admin-forms'),
    path('testing/', TemplateView.as_view(template_name='testing.html'), name='testing'),
    path('data-upload/', user_passes_test(lambda u: u.is_superuser, login_url='403')(otherm_views.process_influx_protocol), name='data-upload'),
    path('data-download/', otherm_views.DataDownloadFormView.as_view(), name='data-download'),
    path('model-upload/', user_passes_test(lambda u: u.is_superuser, login_url='403')(otherm_views.model_upload_view), name='model-upload'),
    path('site-list/', otherm_views.SiteListView.as_view(), name='site-list'),
    path('site-registration/', otherm_views.SiteCreate.as_view(), name='site-registration'),
    path('thermal-load/', otherm_views.ThermalLoadCreate.as_view(), name='thermal-load'),
    path('site-source-registration/', otherm_views.SiteSourceMapCreate.as_view(), name='site-source-registration'),
    path('source-registration/', otherm_views.SourceCreate.as_view(), name='source-registration'),
    path('source-spec-registration/', otherm_views.SourceSpecCreate.as_view(), name='source-spec-registration'),
    path('air-source-spec-form/', otherm_views.AirSourceSpecCreate.as_view(), name='air-source-spec-form'),
    path('standing-column-spec-form/', otherm_views.StandingColumnSpecCreate.as_view(), name='standing-column-spec-form'),
    path('open-loop-spec-form/', otherm_views.OpenLoopSpecCreate.as_view(), name='open-loop-spec-form'),
    path('vertical-loop-spec-form/', otherm_views.VerticalLoopSpecCreate.as_view(), name='vertical-loop-spec-form'),
    path('horizontal-loop-spec-form/', otherm_views.HorizontalLoopSpecCreate.as_view(), name='horizontal-loop-spec-form'),
    path('pond-spec-form/', otherm_views.PondSpecCreate.as_view(), name='pond-spec-form'),
    path('system-spec-list/', user_passes_test(lambda u: u.is_superuser, login_url='403')(otherm_views.MonitoringSystemListView.as_view()), name='system-spec-list'),
    path('system-spec-registration/<int:system_id>/', otherm_views.monitoring_system_spec,
         name='system-spec-registration'),
    path('add-monitoring-system/', otherm_views.EquipmentMonitoringSystemSpecCreate.as_view(), name='add-monitoring-system'),
    path('system-registration/', user_passes_test(lambda u: u.is_superuser, login_url='403')(otherm_views.MonitorSystemCreate.as_view()), name='system-registration'),
    path('equipment-site-list/', otherm_views.EquipmentSiteListView.as_view(), name='equipment-site-list'),
    path('add-equipment/<pk>/', otherm_views.EquipmentCreate.as_view(), name='registration'),
    path('change-monitoring-system-eq-list/', otherm_views.ChangeMonitoringSystemEQlistView.as_view(), name='change-monitoring-system-eq-list'),
    path('change-monitoring-system/<pk>/', otherm_views.ChangeMonitoringSystem.as_view(), name='change-monitoring-system'),
    path('change-monitoring-system-redirect/<int:pk>/', otherm_views.ChangeMonitoringSystemSpecRedirect, name='change-monitoring-system-redirect'),
    path('change-monitoring-system-choice/<pk>/', otherm_views.ChangeMonitoringSystemChoice.as_view(), name='change-monitoring-system-choice'),
    path('delete-equipment/<pk>/', otherm_views.EquipmentDelete.as_view(), name='equipment-delete'),
    path('weather-form/', user_passes_test(lambda u: u.is_superuser, login_url='403')(otherm_views.WeatherFormView.as_view()), name='weather'),
    path('data-audit/', otherm_views.AuditDataView.as_view(), name='audit'),
    path('ajax/load-models/', otherm_views.load_models, name='ajax_load_models'),
    path('ajax/load-manufacturers/', otherm_views.load_manufacturers, name='ajax_load_manufacturers'),
    path('ajax/load-equip-from-site/', otherm_views.load_equipment_from_site, name='ajax_load_equipment_from_site'),
    path('ajax/load_source_spec_form/', otherm_views.load_source_spec_form, name='ajax_load_source_spec_form'),
    path('403/', TemplateView.as_view(template_name='403.html'), name='403'),
]

othermsite/web/othermsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('db/', include('othermdbapp.urls')),
    path('', include('othermdbapp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

othermsite/web/othermdbapp/models.py
import uuid as uuid
from datetime import datetime
from django.contrib.postgres.fields import ArrayField

from django.core.validators import RegexValidator
from django.db import models


class WeatherData(models.Model):
    """Class may not be used.  _rel on field names different than influx db.  Perhaps that is intentional
       WeatherStations is below
    """
    id = models.CharField(primary_key=True, max_length=100)
    latitude = models.FloatField(default=0 )
    longitude = models.FloatField(default=0)
    reliability = models.FloatField()
    temp_rel = models.FloatField()
    wind_speed_rel = models.FloatField()
    barometric_pressure_rel = models.FloatField()
    humidity_rel = models.FloatField()
    dewpoint_rel = models.FloatField()

    class Meta:
        verbose_name_plural = 'weather data'

    def save(self, *args, **kwargs):
        if not self.id:
            self.timestamp = datetime.utcnow()
        return super(WeatherData, self).save(*args, **kwargs)

    def __str__(self):
        return '%s' % (self.site)

    def __unicode__(self):
        return u'%s' % (self.site)


class Manufacturer(models.Model):
    name = models.CharField(unique=True, max_length=20)
    description = models.TextField(blank=True, null=True)
    equipment_type = models.ForeignKey('EquipmentType', models.DO_NOTHING, db_column='type', null=True)

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        db_table = 'manufacturer'


class Model(models.Model):
    id = models.CharField(primary_key=True, max_length=50, help_text='series + capacity, e.g. NVV036')
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.CASCADE)
    equipment_type = models.ForeignKey('EquipmentType', models.DO_NOTHING, db_column='type', null=True)
    model_number = models.CharField(blank=True, null=True, max_length=50, help_text='full model number [optional]')
    def __unicode__(self):
        return u'%s' % (self.id)

    def __str__(self):
        return '%s' % (self.id)

    class Meta:
        db_table = 'model'
        verbose_name = 'Equipment model'



class Equipment(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    name = models.CharField(max_length=50, default="")
    model = models.ForeignKey('Model', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True, help_text='optional')
    type = models.ForeignKey('EquipmentType', models.DO_NOTHING, db_column='type', null=True)
    site = models.ForeignKey('Site', models.DO_NOTHING, db_column='site', blank=True, null=True,
                             help_text='associate equipment with site')
    manufacturer = models.ForeignKey('Manufacturer', models.DO_NOTHING, db_column='manufacturer', blank=True, null=True)
    no_flowmeter_flowrate = models.FloatField(blank=True, null=True, default=None,
                                              help_text='[gpm]: fixed ground loop flow rate when no flowmeter is present')
    maintenance = models.ForeignKey('MaintenanceHistory', on_delete=models.CASCADE, null=True, default=None)

    class Meta:
        db_table = 'equipment'
        verbose_name_plural = 'equipment'

    def __unicode__(self):
        return u'%s-%s-%s' % (self.site, self.model, self.description)

    def __str__(self):
        return '%s-%s-%s' % (self.site, self.model, self.description)


class EquipmentType(models.Model):
    name = models.CharField(unique=True, max_length=20)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        db_table = 'equipment_type'


class EquipmentMonitoringSystemSpec(models.Model):
    equip_id = models.ForeignKey(Equipment, on_delete=models.SET_NULL, db_column='equip_id', blank=True, null=True)
    monitoring_system_spec = models.ForeignKey('MonitoringSystem', models.DO_NOTHING,
                                               db_column='monitoring_system_spec', blank=True, null=True)
    monitoring_system_mac_address = models.CharField(max_length=20, blank=True, null=True, default=' ')
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return u'%s' % (self.monitoring_system_spec)

    def __str__(self):
        return '%s' % (self.monitoring_system_spec)

    class Meta:
        db_table = 'equipment_monitoring_system_spec'


class MeasurementLocation(models.Model):
    name = models.CharField(unique=True, max_length=20)
    description = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'measurement_location'

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)


class MeasurementType(models.Model):
    name = models.CharField(unique=True, max_length=30)
    msp_columns = ArrayField(models.CharField(max_length=30), null=True)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        db_table = 'measurement_type'


class MeasurementUnit(models.Model):
    name = models.CharField(unique=True, max_length=10)
    description = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'measurement_unit'

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)


class MonitoringSystem(models.Model):
    name = models.CharField(unique=True, max_length=40)
    description = models.TextField(blank=True, null=True)
    manufacturer = models.ForeignKey(Manufacturer, models.DO_NOTHING, db_column='manufacturer', blank=True, null=True)

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        db_table = 'monitoring_system'


class MeasurementSpec(models.Model):
    name = models.CharField(unique=True, max_length=30)
    description = models.TextField(blank=True, null=True, help_text='for heat pump power measurements, indicate'
                                                                    'inclusion of pump and/or fan power')
    type = models.ForeignKey('MeasurementType', models.DO_NOTHING, db_column='type')
    accuracy = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True)
    accuracy_pct = models.BooleanField(blank=True, null=True)
    meas_bias_abs = models.FloatField(default=0.0, help_text='measurement bias in units of measurement')
    meas_bias_pct = models.FloatField(default=0.0, help_text='measurement bias as a percent (10%) of reading')
    location = models.ForeignKey(MeasurementLocation, models.DO_NOTHING, db_column='location', blank=True, null=True)
    unit = models.ForeignKey('MeasurementUnit', models.DO_NOTHING, db_column='unit', default=None, null=True)

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        db_table = 'measurement_spec'


class MonitoringSystemSpec(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    monitoring_system = models.ForeignKey(MonitoringSystem, models.DO_NOTHING, db_column='monitoring_system',
                                          blank=True, null=True)
    measurement_type = models.ForeignKey(MeasurementType, models.DO_NOTHING, db_column='measurement_type', blank=True,
                                         null=True)
    measurement_spec = models.ForeignKey(MeasurementSpec, models.DO_NOTHING, db_column='measurement_spec', blank=True,
                                         null=True)

    def __unicode__(self):
        return u'%s-%s' % (self.monitoring_system, self.uuid)

    def __str__(self):
        return '%s-%s' % (self.monitoring_system, self.uuid)

    class Meta:
        db_table = 'monitoring_system_spec'


class Site(models.Model):
    name = models.CharField(unique=True, max_length=50, help_text='M&V program identifier')
    description = models.TextField(blank=True, null=True, help_text='optional')
    city = models.CharField(max_length=60, default='')
    state = models.ForeignKey('State', models.DO_NOTHING, db_column='state', blank=True, null=True)
    zip_code = models.CharField(max_length=9, validators=[RegexValidator(
        regex=r'^[0-9]{5}(?:-[0-9]{4})?$',
        message=u'Must be valid zipcode in formats 12345 or 12345-1234')])
    timezone = models.ForeignKey('Tzone', models.DO_NOTHING, db_column='timezone', blank=True, null=True)
    application = models.CharField(max_length=60, default='', help_text='e.g. retrofit, new construction, etc')
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    thermal_load = models.ForeignKey('ThermalLoad', models.DO_NOTHING, blank=True, null=True)
    weather_station_nws_id = models.ForeignKey('WeatherStation', models.DO_NOTHING, blank=True, null=True)

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        db_table = 'site'


class State(models.Model):
    name = models.CharField(primary_key=True, max_length=40, default='')

    def __unicode__(self):
        return u'%s' % (self.name)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        db_table = 'state'


class Tzone(models.Model):
    tzone_name = models.TextField(primary_key=True)

    def __unicode__(self):
        return u'%s' % (self.tzone_name)

    def __str__(self):
        return '%s' % (self.tzone_name)

    class Meta:
        db_table = 'tzone'

class ThermalLoad(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4)

othermsite/web/othermdbapp/templates/change-monitoring-system-choice.html
{% extends "base.html" %}
{% load custom_tags %}
{% load crispy_forms_tags %}

{% block title %}Select Monitoring System to Change{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="text-center mt-5">Choose Monitoring System to Change</h1>
        <div class="text-center alert alert-danger"> There are multiple monitoring systems with no end_date for this equipment. Please select the EquipmentMonitoringSystemSpec entry to change. </div>
        <button onclick="window.location.href = '/'" class="btn btn-secondary">Home</button>
        <!-- This will tell the user if the equipmentmonitoringsystemspec was modified successfully -->
        <!-- All sites will be displayed in the following table -->
        <table class="mt-2 table table-striped">
            <thead>
            <tr>
                <th scope="col">Monitoring System Spec</th>
                <th scope="col">Start Date</th>
                <th scope="col">Equipment</th>
                <th class="text-center" scope="col"></th>

            </tr>
            </thead>
            <tbody>
            {% for spec in object_list %}
                <tr>
                    <td>{{ spec.monitoring_system_spec }}</td>
                    <td>{{ spec.start_date }}</td>
                    <td>{{ spec.equip_id }}</td>
                    <td class="text-center"><a class="btn btn-info" href="{% url 'change-monitoring-system' spec.pk %}"
                                               role="button">Select</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    <!--Render the previous button-->
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link"
                                                 href="/change-monitoring-system-choice/?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}

                    <!-- Render paginated buttons -->
                    {% for page_num in page_obj.paginator.page_range %}
                        <!-- Set the current page as active if the page number we are on is the same -->
                        {% if page_num is page_obj.number %}
                            <li class="active page-item"><a class="page-link"
                                                            href="/change-monitoring-system-choice/?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item"><a class="page-link"
                                                     href="/change-monitoring-system-choice/?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <!--Render the next button-->
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link"
                                                 href="/change-monitoring-system-choice/?page={{ page_obj.next_page_number }}">Next</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock content %}

othermsite/web/othermdbapp/templates/danger-message.html
{% for message in messages %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

othermsite/web/othermdbapp/templates/data_upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
        <h1 class="pt-3 text-center">Upload Data to Time Series Database</h1>
	{% if messages %}
	   {% for message in messages %}	
	   	{% if message.tags == 'success' %}
			<div class="alert alert-success" role="alert">
				{{ message }}
			</div>	
		{% elif message.tags == 'error' %}
			<div class="alert alert-danger" role="alert">
				{{ message }}
			</div>
		{% endif %}
	    {% endfor %}
	{% endif %}
	<button onclick="window.location.href = '/'" class="btn btn-secondary">Home</button>
  	<hr class="mb-3"/>
        <ul class="nav nav-tabs" id="tabs" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="file-tab" data-toggle="tab" href="#file" role="tab" aria-controls="file" aria-selected="true">File Upload</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="text-tab" data-toggle="tab" href="#text" role="tab" aria-controls="text" aria-selected="false">Text Input</a>
            </li>
        </ul>
        <div class="tab-content" id="forms">
            <div class="tab-pane fade show active" id="file" role="tabpanel" aria-labelledby="file-tab">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ fileForm|crispy }}
                    <button type="submit" class="btn btn-primary" name="fileForm">Upload</button>
                </form>
            </div>
            <div class="tab-pane fade" id="text" role="tabpanel" aria-labelledby="text-tab">
                <form method="post">
                    {% csrf_token %}
                    {{ textForm|crispy }}
                    <button type="submit" class="btn btn-primary" name="textForm">Upload</button>
                </form>
            </div>
        </div>
</div>
{% endblock %}

othermsite/web/othermdbapp/templates/eq.html
{% if eqv_objs %}
    <table>
        {% for eqv in eqv_objs %}
            <tr>
                <td>{{ eqv.equipment_uuid }}</td>
                <td>{{ eqv.company_name }}</td>
                <td>{{ eqv.equipment_name }}</td>
                <td>{{ eqv.description }}</td>
                <td>{{ eqv.equipment_type }}</td>
                <td>{{ eqv.site_name }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Something went wrong</p>
{% endif %}

othermsite/web/othermdbapp/templates/equipment-confirm-delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Update Equipment to a Site{% endblock %}
{% block content %}
    <div class="container">
        <div class="mt-5 row justify-content-center">
            <form class="text-center" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete the record for {{ object.manufacturer }} {{ object.model }}?</p>
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
        </div>

    </div>
{% endblock content %}

othermsite/web/othermdbapp/templates/equipment-dropdown-options.html
<!--Helps in rendering the equipment in the dropdown-->
<option value="">---------</option>
{% for equip in equipment %}
    <option value="{{ equip.pk }}">{{ equip }}</option>
{% endfor %}

othermsite/web/othermdbapp/templates/equipment-registration.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Equipment to a Site{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="pt-3 text-center">Add Equipment to {{ site_name }}</h1>
        <button onclick="window.location.href = '/site-list/'" class="btn btn-secondary">Back to Site List</button>
        <hr class="mb-3"/>
        <form id="equipmentRegistrationForm" method="POST" data-manufacturer-url="{% url 'ajax_load_manufacturers' %}"
              data-model-url="{% url 'ajax_load_models' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <!-- All sites will be displayed in the following table -->
        <h2 class="mt-5">Equipment at {{ site_name }}</h2>
        <table class="mt-2 table table-striped">
            <thead>
            <tr>
                <th scope="col">UUID (Last Four)</th>
                <th scope="col">Type</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
                <th class="text-center" scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for equipment in equipment_list %}
                <tr>
                    <!-- UUID is sliced so that only the last 4 digits are displayed -->
                    <td>{{ equipment.uuid|slugify|slice:"-4:" }}</td>
                    <td>{{ equipment.type }}</td>
                    <td>{{ equipment.manufacturer }}</td>
                    <td>{{ equipment.model }}</td>
                    <td class="text-center"><a class="btn btn-danger" href="{% url 'equipment-delete' equipment.pk %}"
                                               role="button">Delete</a></td>
                </tr>
            {% empty %}
                <tr>
                    <td>No Equipment to display</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock content %}

{% block footer_javascript_page %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>
        // Loads the manufacturer dropdown based off of the equipment type
        $("#id_type").change(function () {
            // get the url of the `data-manufacturer-url` view
            var url = $("#equipmentRegistrationForm").attr("data-manufacturer-url");
            // get the selected type ID from the HTML input
            var type_id = $(this).val();

            $.ajax({
                url: url,                           // set the url of the request (= localhost:8000/data-manufacturer-url/)
                data: {
                    'equipment_type': type_id       // add the equipment type id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `data-manufacturer-url` view function
                    // replace the contents of the manufacturer input with the data that came from the server
                    $("#id_manufacturer").html(data);
                }
            });
        });
    </script>

    <script>
        // Loads the models to the dropdown based on the selected manufacturer
        $("#id_manufacturer").change(function () {
            // get the url of the `data-model-url` view
            var url = $("#equipmentRegistrationForm").attr("data-model-url");
            // get the manufacturer ID from the HTML input
            var manufacturer_id = $(this).val();

            $.ajax({
                url: url,                                 // set the url of the request (= localhost:8000/data-model-url/)
                data: {
                    'manufacturer': manufacturer_id       // add the manufacturer id to the GET parameters
                },
                success: function (data) {      // `data` is the return of the `data-model-url` view function
                    // replace the contents of the model input with the data that came from the server
                    $("#id_model").html(data);
                }
            });
        });
    </script>
{% endblock footer_javascript_page %}

othermsite/web/othermdbapp/templates/horizontal-loop-spec-form.html
{% load crispy_forms_tags %}
<form class="form-horizontal" method="POST" action="/horizontal-loop-spec-form/">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Register</button>
</form>

othermsite/web/othermdbapp/templates/open-loop-spec-form.html
{% load crispy_forms_tags %}
<form class="form-horizontal" method="POST" action="/open-loop-spec-form/">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Register</button>
</form>

othermsite/web/othermdbapp/templates/source-spec-registration.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h3 class="text-center mt-5">Thermal Source Spec Registration</h3>
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
        {{ message }}
    </div>
    {% else %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    <button onclick="window.location.href = '/'" class="btn btn-secondary">Home</button>
    <hr />
    <div class="form-group">
        <label for="id_type" class=" requiredField">
            Type</span>
        </label>
        <div class=""> <select name="type" class="select form-control" required="" id="id_type">
                <option value="" selected=""></option>
                <option value="AirSourceSpec">AirSourceSpec</option>
                <option value="StandingColumnSpec">StandingColumnSpec</option>
                <option value="OpenLoopSpec">OpenLoopSpec</option>
                <option value="VerticalLoopSpec">VerticalLoopSpec</option>
                <option value="HorizontalLoopSpec">HorizontalLoopSpec</option>
                <option value="PondSpec">PondSpec</option>
            </select>
        </div>
    </div>
    <span id="formContainer">
    </span>
</div>


{% endblock content %}


{% block footer_javascript_page %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    // Loads the manufacturer dropdown based off of the equipment type
    $("#id_type").change(function () {
        var type_id = $(this).val();
        if (type_id === '') return;

        // get the url of the `data-manufacturer-url` view
        var url = "{% url 'ajax_load_source_spec_form' %}"
        // get the selected type ID from the HTML input
        var type_id = $(this).val();

        $.ajax({
            url: url,
            data: {
                'spec_type': type_id
            },
            success: function (data) {
                $("#formContainer").html(data);
            }
        });
    });
</script>
{% endblock footer_javascript_page %}